-- =============================================================================
-- Préstamo de Videobeams · UNIPAZ — esquema para Supabase
-- -----------------------------------------------------------------------------
-- Ejecutar completo en: Supabase > SQL Editor > New query > Run.
-- Es re-ejecutable: no borra datos existentes.
--
-- La página index.html es pública y la clave de Supabase también, así que toda
-- la seguridad vive aquí:
--   * RLS en todas las tablas.
--   * Las solicitudes solo se escriben a través de funciones (RPC) que validan
--     permisos, anticipación mínima y disponibilidad.
--   * La restricción EXCLUDE de `solicitudes` impide que un videobeam quede
--     reservado dos veces en horarios que se cruzan, incluso con peticiones
--     simultáneas.
--   * Un trigger en auth.users rechaza correos fuera del dominio institucional,
--     tanto para Google como para usuario y contraseña.
--
-- Para dar permisos de administrador (después de que el usuario exista):
--   update public.perfiles set es_admin = true where email = 'admin@unipaz.edu.co';
-- =============================================================================

create extension if not exists btree_gist with schema extensions;


-- =============================================================================
-- Tablas
-- =============================================================================

-- Una sola fila. Se edita desde Supabase > Table Editor.
create table if not exists public.configuracion (
    id boolean primary key default true check (id),
    dominio_institucional text not null default 'unipaz.edu.co',
    dias_anticipacion integer not null default 1 check (dias_anticipacion >= 0),
    zona_horaria text not null default 'America/Bogota'
);

insert into public.configuracion (id) values (true) on conflict (id) do nothing;

create table if not exists public.perfiles (
    id uuid primary key references auth.users (id) on delete cascade,
    nombre text not null,
    email text not null unique,
    avatar_url text,
    es_admin boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.sedes (
    id bigint generated by default as identity primary key,
    nombre text not null check (length(trim(nombre)) between 1 and 255),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.programas (
    id bigint generated by default as identity primary key,
    nombre text not null check (length(trim(nombre)) between 1 and 255),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.asignaturas (
    id bigint generated by default as identity primary key,
    nombre text not null check (length(trim(nombre)) between 1 and 255),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.equipos (
    id bigint generated by default as identity primary key,
    codigo text not null unique check (length(trim(codigo)) between 1 and 50),
    nombre text check (length(nombre) <= 255),
    sede_id bigint references public.sedes (id) on delete set null,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.solicitudes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.perfiles (id),
    sede_id bigint not null references public.sedes (id),
    aula text not null check (length(trim(aula)) between 1 and 255),
    programa_id bigint not null references public.programas (id),
    asignatura_id bigint not null references public.asignaturas (id),
    actividad text check (length(actividad) <= 255),
    fecha date not null,
    hora_inicio time not null,
    hora_fin time not null,
    equipo_id bigint not null references public.equipos (id),
    evidencia_path text,
    observaciones text check (length(observaciones) <= 1000),
    estado text not null default 'confirmada'
        check (estado in ('pendiente', 'confirmada', 'cancelada', 'rechazada')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint solicitudes_horario_valido check (hora_fin > hora_inicio),

    -- Un equipo no puede tener dos solicitudes activas que se crucen en el tiempo.
    constraint solicitudes_sin_solapes exclude using gist (
        equipo_id with =,
        tsrange(fecha + hora_inicio, fecha + hora_fin, '[)') with &&
    ) where (estado in ('pendiente', 'confirmada'))
);

create index if not exists solicitudes_user_id_idx on public.solicitudes (user_id);
create index if not exists solicitudes_fecha_idx on public.solicitudes (fecha);


-- =============================================================================
-- Funciones auxiliares
-- =============================================================================

-- Fecha actual en la zona horaria de la institución (no en UTC).
create or replace function public.hoy()
returns date
language sql
stable
set search_path = ''
as $$
    select (now() at time zone (select c.zona_horaria from public.configuracion c))::date;
$$;

-- SECURITY DEFINER para poder usarla dentro de las políticas de `perfiles`
-- sin caer en recursión de RLS.
create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select coalesce((select p.es_admin from public.perfiles p where p.id = auth.uid()), false);
$$;

create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();

    return new;
end;
$$;

drop trigger if exists sedes_updated_at on public.sedes;
create trigger sedes_updated_at before update on public.sedes
    for each row execute function public.actualizar_updated_at();

drop trigger if exists programas_updated_at on public.programas;
create trigger programas_updated_at before update on public.programas
    for each row execute function public.actualizar_updated_at();

drop trigger if exists asignaturas_updated_at on public.asignaturas;
create trigger asignaturas_updated_at before update on public.asignaturas
    for each row execute function public.actualizar_updated_at();

drop trigger if exists equipos_updated_at on public.equipos;
create trigger equipos_updated_at before update on public.equipos
    for each row execute function public.actualizar_updated_at();

drop trigger if exists solicitudes_updated_at on public.solicitudes;
create trigger solicitudes_updated_at before update on public.solicitudes
    for each row execute function public.actualizar_updated_at();


-- =============================================================================
-- Registro de usuarios: solo dominio institucional
-- =============================================================================

-- Se ejecuta al crear cualquier usuario en Supabase Auth (Google, contraseña o
-- desde el panel). Si el correo no es institucional, la creación falla.
create or replace function public.registrar_perfil()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_dominio text := (select c.dominio_institucional from public.configuracion c);
begin
    if lower(split_part(coalesce(new.email, ''), '@', 2)) is distinct from lower(v_dominio) then
        raise exception 'Solo se permiten correos institucionales @%', v_dominio;
    end if;

    insert into public.perfiles (id, nombre, email, avatar_url)
    values (
        new.id,
        coalesce(
            nullif(new.raw_user_meta_data ->> 'full_name', ''),
            nullif(new.raw_user_meta_data ->> 'name', ''),
            split_part(new.email, '@', 1)
        ),
        new.email,
        coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture')
    );

    return new;
end;
$$;

drop trigger if exists al_crear_usuario on auth.users;
create trigger al_crear_usuario
    after insert on auth.users
    for each row execute function public.registrar_perfil();

-- Crea el perfil de usuarios institucionales que ya existían antes de este script.
insert into public.perfiles (id, nombre, email, avatar_url)
select
    u.id,
    coalesce(
        nullif(u.raw_user_meta_data ->> 'full_name', ''),
        nullif(u.raw_user_meta_data ->> 'name', ''),
        split_part(u.email, '@', 1)
    ),
    u.email,
    coalesce(u.raw_user_meta_data ->> 'avatar_url', u.raw_user_meta_data ->> 'picture')
from auth.users u
where lower(split_part(u.email, '@', 2)) = (select lower(c.dominio_institucional) from public.configuracion c)
on conflict (id) do nothing;


-- =============================================================================
-- Seguridad a nivel de fila (RLS)
-- =============================================================================

alter table public.configuracion enable row level security;
alter table public.perfiles enable row level security;
alter table public.sedes enable row level security;
alter table public.programas enable row level security;
alter table public.asignaturas enable row level security;
alter table public.equipos enable row level security;
alter table public.solicitudes enable row level security;

-- La página de login necesita el dominio antes de que exista una sesión.
drop policy if exists "configuracion: lectura pública" on public.configuracion;
create policy "configuracion: lectura pública" on public.configuracion
    for select to anon, authenticated
    using (true);

-- Nadie edita perfiles desde la página (es_admin se cambia por SQL).
drop policy if exists "perfiles: ver el propio o admin" on public.perfiles;
create policy "perfiles: ver el propio o admin" on public.perfiles
    for select to authenticated
    using (id = (select auth.uid()) or (select public.es_admin()));

-- Catálogos: cualquier usuario autenticado los lee; solo admin crea y edita.
do $$
declare
    v_tabla text;
begin
    foreach v_tabla in array array['sedes', 'programas', 'asignaturas', 'equipos'] loop
        execute format('drop policy if exists "%1$s: lectura" on public.%1$I', v_tabla);
        execute format(
            'create policy "%1$s: lectura" on public.%1$I for select to authenticated using (true)',
            v_tabla
        );

        execute format('drop policy if exists "%1$s: admin crea" on public.%1$I', v_tabla);
        execute format(
            'create policy "%1$s: admin crea" on public.%1$I for insert to authenticated with check ((select public.es_admin()))',
            v_tabla
        );

        execute format('drop policy if exists "%1$s: admin edita" on public.%1$I', v_tabla);
        execute format(
            'create policy "%1$s: admin edita" on public.%1$I for update to authenticated using ((select public.es_admin())) with check ((select public.es_admin()))',
            v_tabla
        );
    end loop;
end;
$$;

-- Solicitudes: cada docente ve las suyas y el admin ve todas. No hay políticas
-- de escritura: se crean, editan y cancelan solo mediante las funciones de abajo.
drop policy if exists "solicitudes: ver propias o admin" on public.solicitudes;
create policy "solicitudes: ver propias o admin" on public.solicitudes
    for select to authenticated
    using (user_id = (select auth.uid()) or (select public.es_admin()));

revoke insert, update, delete on public.configuracion, public.perfiles, public.solicitudes from anon, authenticated;


-- =============================================================================
-- Funciones que llama la página (RPC)
-- =============================================================================

-- Crea (p_id = null) o edita una solicitud. Si p_equipo_id es null asigna el
-- primer videobeam activo libre en ese horario.
-- Los errores de validación llevan en DETAIL el nombre del campo afectado.
create or replace function public.guardar_solicitud(
    p_id bigint,
    p_sede_id bigint,
    p_aula text,
    p_programa_id bigint,
    p_asignatura_id bigint,
    p_actividad text,
    p_fecha date,
    p_hora_inicio time,
    p_hora_fin time,
    p_equipo_id bigint,
    p_evidencia_path text,
    p_observaciones text
)
returns public.solicitudes
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_usuario uuid := auth.uid();
    v_existente public.solicitudes;
    v_fecha_minima date := public.hoy() + (select c.dias_anticipacion from public.configuracion c);
    v_equipo_id bigint;
    v_resultado public.solicitudes;
begin
    if v_usuario is null then
        raise exception 'Debes iniciar sesión.' using errcode = '42501';
    end if;

    if p_id is not null then
        select * into v_existente from public.solicitudes s where s.id = p_id for update;

        if not found then
            raise exception 'La solicitud no existe.';
        end if;

        if not (
            public.es_admin()
            or (v_existente.user_id = v_usuario and v_existente.estado = 'confirmada' and v_existente.fecha > public.hoy())
        ) then
            raise exception 'No tienes permiso para editar esta solicitud.' using errcode = '42501';
        end if;
    end if;

    p_aula := nullif(trim(p_aula), '');
    p_actividad := nullif(trim(p_actividad), '');
    p_observaciones := nullif(trim(p_observaciones), '');

    if p_sede_id is null then
        raise exception 'Seleccione una sede.' using detail = 'sede_id';
    end if;

    if p_aula is null then
        raise exception 'Indique el aula.' using detail = 'aula';
    end if;

    if p_programa_id is null then
        raise exception 'Seleccione un programa.' using detail = 'programa_id';
    end if;

    if p_asignatura_id is null then
        raise exception 'Seleccione una asignatura.' using detail = 'asignatura_id';
    end if;

    if p_fecha is null or p_fecha < v_fecha_minima then
        raise exception 'La fecha debe ser igual o posterior al %.', to_char(v_fecha_minima, 'DD/MM/YYYY')
            using detail = 'fecha';
    end if;

    if p_hora_inicio is null then
        raise exception 'Indique la hora de inicio.' using detail = 'hora_inicio';
    end if;

    if p_hora_fin is null or p_hora_fin <= p_hora_inicio then
        raise exception 'La hora de finalización debe ser posterior a la de inicio.' using detail = 'hora_fin';
    end if;

    -- Una evidencia nueva debe estar en la carpeta del usuario que guarda.
    if p_evidencia_path is not null
        and p_evidencia_path is distinct from v_existente.evidencia_path
        and split_part(p_evidencia_path, '/', 1) <> v_usuario::text then
        raise exception 'La evidencia no es válida.' using detail = 'evidencia';
    end if;

    if p_equipo_id is not null and not exists (
        select 1
        from public.equipos e
        where e.id = p_equipo_id
          and (e.activo or e.id = v_existente.equipo_id)
    ) then
        raise exception 'El videobeam seleccionado no está disponible.' using detail = 'equipo_id';
    end if;

    -- La restricción solicitudes_sin_solapes decide si el equipo está libre:
    -- si choca, se prueba el siguiente equipo.
    for v_equipo_id in
        select e.id
        from public.equipos e
        where case when p_equipo_id is null then e.activo else e.id = p_equipo_id end
        order by e.id
    loop
        begin
            if p_id is null then
                insert into public.solicitudes (
                    user_id, sede_id, aula, programa_id, asignatura_id, actividad,
                    fecha, hora_inicio, hora_fin, equipo_id, evidencia_path, observaciones, estado
                )
                values (
                    v_usuario, p_sede_id, p_aula, p_programa_id, p_asignatura_id, p_actividad,
                    p_fecha, p_hora_inicio, p_hora_fin, v_equipo_id, p_evidencia_path, p_observaciones, 'confirmada'
                )
                returning * into v_resultado;
            else
                update public.solicitudes s
                set sede_id = p_sede_id,
                    aula = p_aula,
                    programa_id = p_programa_id,
                    asignatura_id = p_asignatura_id,
                    actividad = p_actividad,
                    fecha = p_fecha,
                    hora_inicio = p_hora_inicio,
                    hora_fin = p_hora_fin,
                    equipo_id = v_equipo_id,
                    evidencia_path = coalesce(p_evidencia_path, s.evidencia_path),
                    observaciones = p_observaciones
                where s.id = p_id
                returning * into v_resultado;
            end if;

            return v_resultado;
        exception
            when exclusion_violation then
                null;
        end;
    end loop;

    if p_equipo_id is not null then
        raise exception 'Ese equipo ya está reservado en el horario seleccionado.' using detail = 'equipo_id';
    end if;

    raise exception 'No hay videobeams disponibles en el horario seleccionado.' using detail = 'equipo_id';
end;
$$;

-- El docente cancela su propia solicitud activa con fecha futura.
create or replace function public.cancelar_solicitud(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_solicitud public.solicitudes;
begin
    select * into v_solicitud from public.solicitudes s where s.id = p_id for update;

    if not found or v_solicitud.user_id is distinct from auth.uid() then
        raise exception 'No tienes permiso para cancelar esta solicitud.' using errcode = '42501';
    end if;

    if v_solicitud.estado not in ('pendiente', 'confirmada') or v_solicitud.fecha <= public.hoy() then
        raise exception 'Esta solicitud ya no se puede cancelar.';
    end if;

    update public.solicitudes s set estado = 'cancelada' where s.id = p_id;
end;
$$;

-- El admin cambia el estado de cualquier solicitud.
create or replace function public.cambiar_estado_solicitud(p_id bigint, p_estado text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if not public.es_admin() then
        raise exception 'Solo un administrador puede cambiar el estado.' using errcode = '42501';
    end if;

    if p_estado is null or p_estado not in ('pendiente', 'confirmada', 'cancelada', 'rechazada') then
        raise exception 'Estado no válido.';
    end if;

    update public.solicitudes s set estado = p_estado where s.id = p_id;

    if not found then
        raise exception 'La solicitud no existe.';
    end if;
exception
    when exclusion_violation then
        raise exception 'No se puede cambiar el estado: ese equipo ya está reservado en ese horario.';
end;
$$;

-- Reservas activas para el calendario entre p_inicio (incluido) y p_fin
-- (excluido, como lo envía FullCalendar). Expone solo lo necesario de las
-- solicitudes de otros docentes (no aula, observaciones ni evidencia).
create or replace function public.eventos_calendario(p_inicio date, p_fin date)
returns table (
    id bigint,
    fecha date,
    hora_inicio time,
    hora_fin time,
    estado text,
    equipo_id bigint,
    equipo text,
    asignatura text,
    docente text
)
language sql
stable
security definer
set search_path = ''
as $$
    select s.id, s.fecha, s.hora_inicio, s.hora_fin, s.estado, s.equipo_id, e.codigo, a.nombre, p.nombre
    from public.solicitudes s
    join public.equipos e on e.id = s.equipo_id
    join public.asignaturas a on a.id = s.asignatura_id
    join public.perfiles p on p.id = s.user_id
    where auth.uid() is not null
      and s.estado in ('pendiente', 'confirmada')
      and s.fecha >= p_inicio
      and s.fecha < p_fin;
$$;

revoke execute on function
    public.guardar_solicitud,
    public.cancelar_solicitud,
    public.cambiar_estado_solicitud,
    public.eventos_calendario
from public, anon;

grant execute on function
    public.guardar_solicitud,
    public.cancelar_solicitud,
    public.cambiar_estado_solicitud,
    public.eventos_calendario
to authenticated;


-- =============================================================================
-- Almacenamiento de evidencias (privado, imágenes de máximo 4 MB)
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('evidencias', 'evidencias', false, 4194304, array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Cada usuario sube a su carpeta: evidencias/<user_id>/archivo.jpg
drop policy if exists "evidencias: subir en carpeta propia" on storage.objects;
create policy "evidencias: subir en carpeta propia" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'evidencias' and (storage.foldername(name))[1] = (select auth.uid()::text));

drop policy if exists "evidencias: ver propias o admin" on storage.objects;
create policy "evidencias: ver propias o admin" on storage.objects
    for select to authenticated
    using (
        bucket_id = 'evidencias'
        and ((storage.foldername(name))[1] = (select auth.uid()::text) or (select public.es_admin()))
    );

-- Solo se pueden borrar archivos propios que ninguna solicitud usa (limpieza
-- cuando falla el guardado después de subir la imagen).
drop policy if exists "evidencias: borrar propias sin usar" on storage.objects;
create policy "evidencias: borrar propias sin usar" on storage.objects
    for delete to authenticated
    using (
        bucket_id = 'evidencias'
        and (storage.foldername(name))[1] = (select auth.uid()::text)
        and not exists (select 1 from public.solicitudes s where s.evidencia_path = objects.name)
    );


-- =============================================================================
-- Datos iniciales (mismos que el DatabaseSeeder de Laravel)
-- =============================================================================

insert into public.sedes (nombre)
select v.nombre
from (values ('Sede Principal'), ('Centro Santa Lucía'), ('Colegio de las Américas (jornada nocturna)')) as v (nombre)
where not exists (select 1 from public.sedes s where s.nombre = v.nombre);

insert into public.programas (nombre)
select v.nombre
from (values ('Trabajo Social'), ('Psicología'), ('Sociología')) as v (nombre)
where not exists (select 1 from public.programas p where p.nombre = v.nombre);

insert into public.asignaturas (nombre)
select v.nombre
from (values ('Investigación Social I'), ('Trabajo Social Comunitario'), ('Psicología Educativa')) as v (nombre)
where not exists (select 1 from public.asignaturas a where a.nombre = v.nombre);

insert into public.equipos (codigo, sede_id)
select
    'VB-' || lpad(n::text, 2, '0'),
    (select s.id from public.sedes s where s.nombre = 'Sede Principal' order by s.id limit 1)
from generate_series(1, 8) as n
on conflict (codigo) do nothing;
